name: Metrics

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: ed-radanovis
          template: classic
          base: ""
          config_timezone: America/Sao_Paulo

          # OBRIGA o GitHub Metrics a usar apenas repositórios escolhidos
          repositories_affiliations: owner
          repositories: |
            ed-radanovis/Engenharia_Software_Repositorio_Central-01-2025_a_10-2028

          # Linguagens APENAS do repo acima
          plugin_languages: yes
          plugin_languages_sections: most-used
          plugin_languages_indepth: yes
          plugin_languages_indepth_custom: |
            ed-radanovis/Engenharia_Software_Repositorio_Central-01-2025_a_10-2028
          plugin_languages_threshold: 0%

          filename: github-metrics.svg
